version: "3.8"
services:
  criminal-signal-flztrgt:
    build: .
    container_name: criminal-signal-flztrgt
    environment:
      - SCREEN_GEOM=1366x768x24
      - NOVNC_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    restart: unless-stopped
